# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'hanko-ruby', path: '../hanko'

rails_version = ENV.fetch('RAILS_VERSION', '8.0')
gem 'rails', "~> #{rails_version}.0"

group :development, :test do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
  gem 'rspec-rails', '~> 7.0'
  gem 'simplecov', '~> 0.22', require: false
  gem 'webmock', '~> 3.19'
end
